# Generated by Django 6.0.3 on 2026-04-01 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('cod_doc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id_ramo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('folio', models.AutoField(primary_key=True, serialize=False)),
                ('nom_alu', models.CharField(max_length=100)),
                ('nota_final', models.DecimalField(decimal_places=1, max_digits=4)),
                ('estado', models.CharField(choices=[('AP', 'Aprobado'), ('RP', 'Reprobado')], max_length=2)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docente')),
                ('ramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ramo')),
            ],
        ),
    ]
