# Generated by Django 6.0.3 on 2026-04-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_informe_apell_alu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='apell_alu',
        ),
    ]
